# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-test .
      
      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-test

  deploys:
    needs: build
    runs-on: self-hosted
    steps:
     - name: Docker pull
       run: docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd-test
     - name: Delete old container
       run: docker rm -f ci-cd-test
     - name: Run docker container
       run: docker run -d -p 8090:8090 --name ci-cd-test ${{ secrets.DOCKER_USERNAME }}/ci-cd-test
      
